# Generated by Django 2.2.24 on 2022-09-29 14:31

from django.db import migrations


def fill_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if flat.construction_year < 2015:
            flat.new_building = False
        else:
            flat.new_building = True
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20220925_1648'),
    ]

    operations = [
        migrations.RunPython(fill_new_building),
    ]
